project:
  type: website

website:
  title: "Public Health Simulation"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: "mailto:tbs204@exeter.ac.uk"
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

