project:
  type: website

website:
  title: "Public Health Simulation"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: "mailto:tbs204@exeter.ac.uk"
      - text: "{{< iconify fa-brands:orcid >}}"
        href: https://orcid.org/0009-0007-0838-7499
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-slater-140107215/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

